### PR TITLE
adding support for validator id

### PR DESCRIPTION
**Pull request by alexdrans**
Useful library, thanks for creating it. We had a need to reference a validator created in Terraform.

### CODE REVIEW

**Comment by RafPe** [comment]
Thanks for the PR 😀 will take a look tomorrow in detail

**Comment by alexdrans** [comment]
> Thanks for the PR 😀 will take a look tomorrow in detail

Hey, just a reminder if you have time

**Review by RafPe — APPROVED** [review]
🚀  ltgm

**Comment by alexdrans** [comment]
> 🚀 ltgm

Thank you! Please release when you can

**Comment by RafPe** [comment]
> > 🚀 ltgm
> 
> Thank you! Please release when you can

It has been already ;) https://www.npmjs.com/package/serverless-reqvalidator-plugin/v/3.1.0

**Pull request merged**
